CREATE DATABASE IF NOT EXISTS burgers_db;

USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    burger_name VARCHAR(70) NOT NULL,
    devoured BOOLEAN NOT NULL
);